### ISSUE TITLE
Consider abandoning Web UI?

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/pm-ipfs-gui#4]
We could instead ship ipfs-companion with go-ipfs and js-ipfs. There's a ton of overlap and we could avoid some of that, as well as the burden of maintenance and harmonization.

**Comment by lidel** [comment]
A lot changed since december. Namely, `window.ipfs` got introduced and it is slowly changing the way we think about building things that use IPFS API.

Closing this one, as follow-up discussion continued in https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/41. **tl;dr** starts from https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/41#issuecomment-374775995
